[build]
builder = "nixpacks"
nixpacksVersion = "1.15.0"

[deploy]
startCommand = "npm start"
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on-failure"
restartPolicyMaxRetries = 3

# Let Railway assign the port dynamically
# [deploy.envs]
# PORT = "3000" 